# Generated by Django 5.2.8 on 2025-12-05 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='erro_envio',
        ),
        migrations.RemoveField(
            model_name='email',
            name='pendente',
        ),
    ]
