# Generated by Django 5.2.6 on 2025-12-06 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_projeto_arquivo_pdf_emenda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emenda',
            name='aprovada',
        ),
        migrations.AddField(
            model_name='emenda',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('aprovada', 'Aprovada'), ('reprovada', 'Reprovada')], default='pendente', max_length=20, verbose_name='Status da Emenda'),
        ),
    ]
