# Generated by Django 5.2.6 on 2025-12-06 06:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_emenda_aprovada_emenda_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='emenda',
            name='data_parecer',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emenda',
            name='justificativa',
            field=models.TextField(blank=True, null=True, verbose_name='Justificativa do Parecer'),
        ),
        migrations.AddField(
            model_name='emenda',
            name='relator_parecer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emendas_avaliadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
